namespace: ahaydon
name: appdaemon
version: 0.1.0
readme: README.md
authors:
  - Adam Haydon (https://github.com/ahaydon)
description: Collection of roles and playbooks for deploying AppDaemon
license_file: LICENSE
tags:
  - appdaemon
  - podman
  - application
  - linux
dependencies:
  "git+https://github.com/ahaydon/ansible-podman-collection.git": "master"
repository: https://github.com/ahaydon/ansible-appdaemon-collection
documentation: https://github.com/ahaydon/ansible-appdaemon-collection
homepage: https://github.com/ahaydon/ansible-appdaemon-collection
issues: https://github.com/ahaydon/ansible-appdaemon-collection/issues
build_ignore: []
